using System;
using Inu.Kernel.AddressSpace;
using Inu.Kernel.Drivers;
using Inu.Kernel.Memory;
using Inu.Kernel.Heap;
using Inu.Kernel.Pci;
using Inu.Kernel.Storage;
namespace Inu.Kernel.Ahci;
/// <summary>AHCI 1.x PCI driver with SATA discovery, DMA command lists, IDENTIFY, read/write and flush.</summary>
public static unsafe partial class KernelAhci
{
 static Boolean FindDisk(KernelDeviceHandle device,out Disk* d){d=null;for(UInt32 i=0;i<_diskCapacity;i++){Disk* x=_disks+i;if(x->Used!=0&&x->DeviceHandle==device.Value){d=x;return true;}}return false;}
 static Int32 FindController(KernelDeviceHandle device){for(Int32 i=0;i<(Int32)_controllerCapacity;i++)if((_controllers+i)->Used!=0&&(_controllers+i)->DeviceHandle==device.Value)return i;return -1;}
 static Int32 FreeController(){for(Int32 i=0;i<(Int32)_controllerCapacity;i++)if((_controllers+i)->Used==0)return i;return -1;}static Int32 FreeDisk(){for(Int32 i=0;i<(Int32)_diskCapacity;i++)if((_disks+i)->Used==0)return i;return -1;}
 static Boolean ReleaseDiskResources(Disk* d){Boolean ok=true;if(d->CommandList.Token!=0)ok=KernelPhysicalMemory.TryRelease(d->CommandList)&ok;if(d->Fis.Token!=0)ok=KernelPhysicalMemory.TryRelease(d->Fis)&ok;if(d->CommandTable.Token!=0)ok=KernelPhysicalMemory.TryRelease(d->CommandTable)&ok;if(d->Bounce.Token!=0)ok=KernelPhysicalMemory.TryRelease(d->Bounce)&ok;d->CommandList=default;d->Fis=default;d->CommandTable=default;d->Bounce=default;return ok;}
 static Boolean AllocateTables(){_controllerCapacity=4U;_diskCapacity=8U;if(!AllocateControllerTable(_controllerCapacity,out _controllerAllocation,out _controllers))return false;if(!AllocateDiskTable(_diskCapacity,out _diskAllocation,out _disks)){KernelHeap.TryRelease(_controllerAllocation);_controllers=null;return false;}return true;}static Boolean GrowControllers(){UInt32 next=_controllerCapacity>0x3FFFFFFFU?UInt32.MaxValue:_controllerCapacity*2U;if(next<=_controllerCapacity)return false;if(!AllocateControllerTable(next,out KernelHeapAllocation a,out Controller* t))return false;CopyBytes((Byte*)_controllers,(Byte*)t,(UInt64)_controllerCapacity*(UInt64)sizeof(Controller));KernelHeapAllocation old=_controllerAllocation;_controllerAllocation=a;_controllers=t;_controllerCapacity=next;return KernelHeap.TryRelease(old);}static Boolean GrowDisks(){UInt32 next=_diskCapacity>0x3FFFFFFFU?UInt32.MaxValue:_diskCapacity*2U;if(next<=_diskCapacity)return false;if(!AllocateDiskTable(next,out KernelHeapAllocation a,out Disk* t))return false;CopyBytes((Byte*)_disks,(Byte*)t,(UInt64)_diskCapacity*(UInt64)sizeof(Disk));KernelHeapAllocation old=_diskAllocation;_diskAllocation=a;_disks=t;_diskCapacity=next;return KernelHeap.TryRelease(old);}static Boolean AllocateControllerTable(UInt32 capacity,out KernelHeapAllocation a,out Controller* t){a=default;t=null;if(!KernelHeap.TryAllocate((UInt64)capacity*(UInt64)sizeof(Controller),64UL,true,out a))return false;t=(Controller*)(nuint)a.Address;return true;}static Boolean AllocateDiskTable(UInt32 capacity,out KernelHeapAllocation a,out Disk* t){a=default;t=null;if(!KernelHeap.TryAllocate((UInt64)capacity*(UInt64)sizeof(Disk),64UL,true,out a))return false;t=(Disk*)(nuint)a.Address;return true;}static Boolean AllocPage(out KernelPhysicalAllocation a)=>KernelPhysicalMemory.TryAllocate(1,1,out a);static Byte* Direct(KernelPhysicalAllocation a)=>(Byte*)(nuint)(KernelAddressSpace.DirectMapBase+a.StartAddress);static void Zero(KernelPhysicalAllocation a){Byte* p=Direct(a);for(UInt32 i=0;i<4096;i++)p[i]=0;}static UInt32 R32(UInt64 b,UInt32 o)=>*(UInt32*)(nuint)(b+o);static void W32(UInt64 b,UInt32 o,UInt32 v)=>*(UInt32*)(nuint)(b+o)=v;static void Clear(Byte* p,UInt64 n){for(UInt64 i=0;i<n;i++)p[i]=0;}static void Copy(Byte* s,Byte* d,UInt32 n){for(UInt32 i=0;i<n;i++)d[i]=s[i];}static void CopyBytes(Byte* s,Byte* d,UInt64 n){for(UInt64 i=0;i<n;i++)d[i]=s[i];}
}
