using System;
using Inu.Kernel.Drivers;
using Inu.Kernel.Heap;
namespace Inu.Bus.Usb;
public static unsafe partial class KernelUsbBus
{
 private static Boolean AddDevice(UsbHostHandle host,Byte address,Byte parent,Byte port,UsbSpeed speed,UsbDeviceDescriptor d,Byte mps,Byte config,out UsbDeviceHandle h){h=default;Int32 slot=FreeDev();if(slot<0)return false;UInt32 cls=d.DeviceClass==0?0U:((UInt32)d.DeviceClass<<16)|((UInt32)d.DeviceSubClass<<8)|d.DeviceProtocol;KernelDeviceIdentifier id=new(KernelDeviceBus.Usb,d.VendorId,d.ProductId,0,0,cls,(Byte)d.DeviceRelease,((UInt32)host.Value<<24)|((UInt32)parent<<16)|((UInt32)port<<8)|address);KernelDeviceHandle parentHandle=hOwner(host);if(parent!=0){parentHandle=default;for(UInt32 pi=0;pi<_deviceCapacity;pi++){DevRec* pd=_devices+pi;if(pd->Used!=0&&pd->Host==host.Value&&pd->Address==parent){parentHandle=new KernelDeviceHandle(pd->Generic);break;}}}if(!KernelDrivers.DiscoverDevice(id,parentHandle,out KernelDeviceHandle generic))return false;DevRec* r=_devices+slot;r->Used=1;r->Host=host.Value;r->Generic=generic.Value;r->Address=address;r->ParentAddress=parent;r->Port=port;r->Speed=(Byte)speed;r->Configuration=config;r->Class=d.DeviceClass;r->SubClass=d.DeviceSubClass;r->Protocol=d.DeviceProtocol;r->MaxPacket0=mps;r->Configs=d.ConfigurationCount;r->Vendor=d.VendorId;r->Product=d.ProductId;r->UsbVersion=d.UsbVersion;r->Release=d.DeviceRelease;KernelDrivers.SetProperty(generic,new KernelDeviceProperty(KernelDevicePropertyKey.UsbAddress,address));KernelDrivers.SetProperty(generic,new KernelDeviceProperty(KernelDevicePropertyKey.UsbPort,port,parent));KernelDrivers.SetProperty(generic,new KernelDeviceProperty(KernelDevicePropertyKey.Flags,(UInt64)speed,config));_deviceCount++;h=new UsbDeviceHandle((UInt32)slot+1);return true;}
 private static Boolean ParseInterfaces(HostRec* host,UsbDeviceHandle dev,Byte* p,UInt32 bytes){IfRec* current=null;UInt32 off=0;if(!TryDev(dev,out DevRec* owner))return false;while(off+2<=bytes){Byte len=p[off],type=p[off+1];if(len<2||off+len>bytes)return false;if(type==(Byte)UsbDescriptorType.Interface){if(current!=null&&!FinalizeInterface(current))return false;if(!UsbDescriptorParser.TryParseInterface(p+off,len,out UsbInterfaceDescriptor d))return false;Int32 s=FreeIf();if(s<0)return false;current=_interfaces+s;Clear((Byte*)current,(UInt32)sizeof(IfRec));current->Used=1;current->Device=dev.Value;current->Number=d.Number;current->Alternate=d.AlternateSetting;current->EndpointCount=d.EndpointCount>4?(Byte)4:d.EndpointCount;current->Class=d.Class;current->SubClass=d.SubClass;current->Protocol=d.Protocol;current->StringIndex=d.StringIndex;UInt32 cls=((UInt32)d.Class<<16)|((UInt32)d.SubClass<<8)|d.Protocol;KernelDeviceIdentifier iid=new(KernelDeviceBus.Usb,owner->Vendor,owner->Product,0,0,cls,0,((UInt32)dev.Value<<8)|d.Number);if(!KernelDrivers.DiscoverDevice(iid,new KernelDeviceHandle(owner->Generic),out KernelDeviceHandle inode)){Clear((Byte*)current,(UInt32)sizeof(IfRec));return false;}current->Generic=inode.Value;_interfaceCount++;}else if(type==(Byte)UsbDescriptorType.Endpoint&&current!=null&&UsbDescriptorParser.TryParseEndpoint(p+off,len,out UsbEndpointDescriptor e)){for(Byte n=0;n<4;n++){if(current->EpAddress[n]!=0)continue;current->EpAddress[n]=e.Address;current->EpAttributes[n]=e.Attributes;current->EpMaxPacket[n]=e.MaximumPacketSize;current->EpInterval[n]=e.Interval;var configure=(delegate*<UInt64,Byte,UsbEndpointDescriptor*,Boolean>)(void*)host->ConfigureEndpoint;if(!configure(host->Context,owner->Address,&e))return false;break;}}off+=len;}if(current!=null&&!FinalizeInterface(current))return false;KernelDeviceHandle ownerNode=new(owner->Generic);if(KernelDrivers.TryBindDevice(ownerNode,out _)&&!KernelDrivers.StartDevice(ownerNode))return false;return true;}
 private static Boolean FinalizeInterface(IfRec* r){if(r==null||r->Generic==0U)return false;KernelDeviceHandle node=new(r->Generic);KernelDrivers.SetProperty(node,new KernelDeviceProperty(KernelDevicePropertyKey.UsbInterface,r->Number,r->Alternate));KernelDrivers.SetProperty(node,new KernelDeviceProperty(KernelDevicePropertyKey.UsbEndpointCount,r->EndpointCount));if(KernelDrivers.TryBindDevice(node,out _))return KernelDrivers.StartDevice(node);return true;}
 private static UsbEndpointDescriptor Ep(IfRec* r,Int32 i)=>new(r->EpAddress[i],r->EpAttributes[i],r->EpMaxPacket[i],r->EpInterval[i]);
 public static Boolean RemoveDevice(UsbDeviceHandle h){if(!TryDev(h,out DevRec* r))return false;UInt32 host=r->Host;Byte address=r->Address;for(UInt32 i=0;i<_deviceCapacity;i++){DevRec* child=_devices+i;if(child->Used!=0&&child->Host==host&&child->ParentAddress==address){if(!RemoveDevice(new UsbDeviceHandle(i+1U)))return false;}}if(!KernelDrivers.RemoveDevice(new KernelDeviceHandle(r->Generic)))return false;for(UInt32 i=0;i<_interfaceCapacity;i++){IfRec* q=_interfaces+i;if(q->Used!=0&&q->Device==h.Value){Clear((Byte*)q,(UInt32)sizeof(IfRec));if(_interfaceCount>0U)_interfaceCount--;}}Clear((Byte*)r,(UInt32)sizeof(DevRec));if(_deviceCount>0U)_deviceCount--;return true;}
}
