using System;
using Inu.Kernel.AddressSpace;
using Inu.Kernel.Drivers;
using Inu.Kernel.Memory;
using Inu.Kernel.Heap;
using Inu.Kernel.Pci;
using Inu.Kernel.Storage;
namespace Inu.Kernel.Nvme;
/// <summary>PCI NVMe 1.x controller driver with admin/I/O queues, namespace discovery and synchronous block I/O.</summary>
public static unsafe partial class KernelNvme
{
 static Boolean FindNamespace(KernelDeviceHandle d,out Namespace* n){n=null;for(UInt32 i=0;i<_namespaceCapacity;i++){Namespace* x=_namespaces+i;if(x->Used!=0&&x->DeviceHandle==d.Value){n=x;return true;}}return false;}
 static Int32 FindController(KernelDeviceHandle device){for(Int32 i=0;i<(Int32)_controllerCapacity;i++)if((_controllers+i)->Used!=0&&(_controllers+i)->DeviceHandle==device.Value)return i;return -1;}
 static Int32 FreeController(){for(Int32 i=0;i<(Int32)_controllerCapacity;i++)if((_controllers+i)->Used==0)return i;return -1;}static Int32 FreeNamespace(){for(Int32 i=0;i<(Int32)_namespaceCapacity;i++)if((_namespaces+i)->Used==0)return i;return -1;}
 static void CleanupNamespaces(UInt32 controller){for(UInt32 i=0;i<_namespaceCapacity;i++){Namespace* n=_namespaces+i;if(n->Used==0||n->Controller!=controller)continue;if(n->StorageHandle!=0U)KernelStorage.UnregisterBlockDevice(new KernelStorageDeviceHandle(n->StorageHandle));if(n->DeviceHandle!=0U)KernelDrivers.RemoveDevice(new KernelDeviceHandle(n->DeviceHandle));Clear((Byte*)n,(UInt64)sizeof(Namespace));if(_namespaceCount>0U)_namespaceCount--;}}
 static Boolean ReleaseControllerResources(Controller* c){Boolean ok=true;if(c->Asq.Token!=0)ok=KernelPhysicalMemory.TryRelease(c->Asq)&ok;if(c->Acq.Token!=0)ok=KernelPhysicalMemory.TryRelease(c->Acq)&ok;if(c->IoSq.Token!=0)ok=KernelPhysicalMemory.TryRelease(c->IoSq)&ok;if(c->IoCq.Token!=0)ok=KernelPhysicalMemory.TryRelease(c->IoCq)&ok;if(c->Identify.Token!=0)ok=KernelPhysicalMemory.TryRelease(c->Identify)&ok;c->Asq=default;c->Acq=default;c->IoSq=default;c->IoCq=default;c->Identify=default;return ok;}
 static Boolean AllocateTables(){_controllerCapacity=8U;_namespaceCapacity=16U;if(!AllocateControllerTable(_controllerCapacity,out _controllerAllocation,out _controllers))return false;if(!AllocateNamespaceTable(_namespaceCapacity,out _namespaceAllocation,out _namespaces)){KernelHeap.TryRelease(_controllerAllocation);_controllers=null;return false;}return true;}
 static Boolean GrowControllers(){UInt32 next=_controllerCapacity>0x3FFFFFFFU?UInt32.MaxValue:_controllerCapacity*2U;if(next<=_controllerCapacity)return false;if(!AllocateControllerTable(next,out KernelHeapAllocation a,out Controller* t))return false;CopyBytes((Byte*)_controllers,(Byte*)t,(UInt64)_controllerCapacity*(UInt64)sizeof(Controller));KernelHeapAllocation old=_controllerAllocation;_controllerAllocation=a;_controllers=t;_controllerCapacity=next;return KernelHeap.TryRelease(old);}
 static Boolean GrowNamespaces(){UInt32 next=_namespaceCapacity>0x3FFFFFFFU?UInt32.MaxValue:_namespaceCapacity*2U;if(next<=_namespaceCapacity)return false;if(!AllocateNamespaceTable(next,out KernelHeapAllocation a,out Namespace* t))return false;CopyBytes((Byte*)_namespaces,(Byte*)t,(UInt64)_namespaceCapacity*(UInt64)sizeof(Namespace));KernelHeapAllocation old=_namespaceAllocation;_namespaceAllocation=a;_namespaces=t;_namespaceCapacity=next;return KernelHeap.TryRelease(old);}
 static Boolean AllocateControllerTable(UInt32 capacity,out KernelHeapAllocation a,out Controller* t){a=default;t=null;if(!KernelHeap.TryAllocate((UInt64)capacity*(UInt64)sizeof(Controller),64UL,true,out a))return false;t=(Controller*)(nuint)a.Address;return true;}
 static Boolean AllocateNamespaceTable(UInt32 capacity,out KernelHeapAllocation a,out Namespace* t){a=default;t=null;if(!KernelHeap.TryAllocate((UInt64)capacity*(UInt64)sizeof(Namespace),64UL,true,out a))return false;t=(Namespace*)(nuint)a.Address;return true;}
 static Boolean AllocPage(out KernelPhysicalAllocation a)=>KernelPhysicalMemory.TryAllocate(1,1,out a); static Byte* Direct(KernelPhysicalAllocation a)=> (Byte*)(nuint)(KernelAddressSpace.DirectMapBase+a.StartAddress); static void Zero(KernelPhysicalAllocation a){Byte* p=Direct(a);for(UInt32 i=0;i<4096;i++)p[i]=0;} static Boolean Fail(Controller* c){if(c==null)return false;c->State=(Byte)NvmeControllerState.Failed;if(c->InterruptHandle!=0UL){KernelDrivers.ReleaseInterrupt(new KernelDriverInterruptHandle(c->InterruptHandle));c->InterruptHandle=0UL;}if(c->Mmio!=0UL)W32(c->Mmio,0x14,0);ReleaseControllerResources(c);Clear((Byte*)c,(UInt64)sizeof(Controller));return false;}
 static UInt32 R32(UInt64 b,UInt32 o)=>*(UInt32*)(nuint)(b+o); static UInt64 R64(UInt64 b,UInt32 o)=>*(UInt64*)(nuint)(b+o); static void W32(UInt64 b,UInt32 o,UInt32 v)=>*(UInt32*)(nuint)(b+o)=v; static void W64(UInt64 b,UInt32 o,UInt64 v)=>*(UInt64*)(nuint)(b+o)=v; static void Clear(Byte* p,UInt64 n){for(UInt64 i=0;i<n;i++)p[i]=0;} static void Copy(Byte* s,Byte* d,UInt32 n){for(UInt32 i=0;i<n;i++)d[i]=s[i];} static void CopyBytes(Byte* s,Byte* d,UInt64 n){for(UInt64 i=0;i<n;i++)d[i]=s[i];}
}
