using System;
using Inu.Kernel.AddressSpace;
using Inu.Kernel.Drivers;
using Inu.Kernel.Memory;
using Inu.Kernel.Heap;
using Inu.Kernel.Pci;
using Inu.Kernel.Storage;
namespace Inu.Kernel.Nvme;
/// <summary>PCI NVMe 1.x controller driver with admin/I/O queues, namespace discovery and synchronous block I/O.</summary>
public static unsafe partial class KernelNvme
{
 static Boolean Probe(KernelDriverDeviceContext* context)=>context!=null&&NvmeMath.IsNvmeClass(context->Identifier.ClassCode)&&KernelPci.TryGetDevice(context->Device,out _);
 static Boolean Start(KernelDriverDeviceContext* context)=>context!=null&&KernelPci.TryGetDevice(context->Device,out PciDeviceInfo pci)&&TryStartController(pci);
 static Boolean Stop(KernelDriverDeviceContext* context){if(context==null)return false;Int32 ci=FindController(context->Device);if(ci<0)return true;Controller* c=_controllers+ci;if(c->InterruptHandle!=0UL&&!KernelDrivers.ReleaseInterrupt(new KernelDriverInterruptHandle(c->InterruptHandle)))return false;c->InterruptHandle=0UL;for(UInt32 i=0;i<_namespaceCapacity;i++){Namespace* n=_namespaces+i;if(n->Used==0||n->Controller!=(UInt32)ci)continue;if(n->StorageHandle!=0U&&!KernelStorage.UnregisterBlockDevice(new KernelStorageDeviceHandle(n->StorageHandle)))return false;if(n->DeviceHandle!=0U&&!KernelDrivers.RemoveDevice(new KernelDeviceHandle(n->DeviceHandle)))return false;Clear((Byte*)n,(UInt64)sizeof(Namespace));if(_namespaceCount>0U)_namespaceCount--;}if(c->Mmio!=0UL){W32(c->Mmio,0x14,0);WaitReady(c,false);}ReleaseControllerResources(c);Clear((Byte*)c,(UInt64)sizeof(Controller));if(_controllerCount>0U)_controllerCount--;return true;}
 static Boolean Remove(KernelDriverDeviceContext* context)=>context!=null&&Stop(context);
 static Boolean Interrupt(KernelDriverDeviceContext* context,UInt64 cookie){if(context==null)return false;Int32 ci=FindController(context->Device);if(ci<0)return false;(_controllers+ci)->InterruptEpoch++;return true;}
 static Boolean TryStartController(PciDeviceInfo pci){if(!KernelPci.TryMapBar(pci.Location,0,out PciBarInfo bar,out UInt64 mmio)||bar.Type==PciBarType.Io||bar.Length<0x2000UL)return false;if(!KernelPci.TryRead16(pci.Location,4,out UInt16 cmd)||!KernelPci.TryWrite16(pci.Location,4,(UInt16)(cmd|0x0006U)))return false;Int32 slot=FreeController();if(slot<0){if(!GrowControllers())return false;slot=FreeController();if(slot<0)return false;}Controller* c=_controllers+slot;Clear((Byte*)c,(UInt64)sizeof(Controller));c->Used=1;c->State=(Byte)NvmeControllerState.Disabled;c->Segment=pci.Location.Segment;c->Bus=pci.Location.Bus;c->Device=pci.Location.Device;c->Function=pci.Location.Function;c->DeviceHandle=pci.DeviceHandle.Value;c->Mmio=mmio;UInt64 cap=R64(mmio,0);UInt32 maximumEntries=(UInt32)(cap&0xFFFFUL)+1U;if(maximumEntries<2U||(cap&(1UL<<37))==0)return Fail(c);c->AdminEntries=(UInt16)(maximumEntries<RequestedAdminEntries?maximumEntries:RequestedAdminEntries);c->IoEntries=(UInt16)(maximumEntries<RequestedIoEntries?maximumEntries:RequestedIoEntries);c->DbStride=(Byte)((cap>>32)&15UL);c->Version=R32(mmio,8);if(((cap>>48)&15UL)!=0UL)return Fail(c);W32(mmio,0x14,0);if(!WaitReady(c,false))return Fail(c);if(!AllocPage(out c->Asq)||!AllocPage(out c->Acq)||!AllocPage(out c->Identify))return Fail(c);Zero(c->Asq);Zero(c->Acq);Zero(c->Identify);W32(mmio,0x24,((UInt32)(c->AdminEntries-1U)<<16)|(UInt32)(c->AdminEntries-1U));W64(mmio,0x28,c->Asq.StartAddress);W64(mmio,0x30,c->Acq.StartAddress);W32(mmio,0x14,(6U<<16)|(4U<<20)|1U);if(!WaitReady(c,true))return Fail(c);c->State=(Byte)NvmeControllerState.Ready;c->InterruptMode=(Byte)NvmeInterruptMode.Synchronous;c->AdminPhase=1;c->IoPhase=1;KernelDriverInterruptRequest interruptRequest=new(pci.DeviceHandle,0U,8,0U,false,false,(UInt64)(UInt32)slot+1UL);if(KernelDrivers.TryRequestInterrupt(interruptRequest,out KernelDriverInterruptHandle interrupt)){c->InterruptHandle=interrupt.Value;c->InterruptMode=(Byte)NvmeInterruptMode.BrokerManaged;W32(mmio,0x10,0xFFFFFFFFU);}if(!AdminIdentify(c,0,1,c->Identify.StartAddress))return Fail(c);Byte* id=Direct(c->Identify);UInt32 nn=*(UInt32*)(id+516);if(!CreateIoQueues(c))return Fail(c);UInt32 controllerIndex=(UInt32)slot;if(!DiscoverActiveNamespaces(controllerIndex,c,nn)){CleanupNamespaces(controllerIndex);return Fail(c);}_controllerCount++;return true;}
}
