<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Library</OutputType><TargetFramework>net10.0</TargetFramework><ImplicitUsings>disable</ImplicitUsings><Nullable>disable</Nullable><DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences><NoStdLib>true</NoStdLib><NoConfig>true</NoConfig><RuntimeMetadataVersion>v4.0.30319</RuntimeMetadataVersion><GenerateAssemblyInfo>false</GenerateAssemblyInfo><GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute><DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences><AllowUnsafeBlocks>true</AllowUnsafeBlocks><AssemblyName>Inu.Usb.MassStorage</AssemblyName></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Inu.Freestanding.CoreLib\Inu.Freestanding.CoreLib.csproj" />
    <ProjectReference Include="..\Inu.Bus.Usb\Inu.Bus.Usb.csproj" />
    <ProjectReference Include="..\Inu.Kernel.Drivers\Inu.Kernel.Drivers.csproj" />
    <ProjectReference Include="..\Inu.Kernel.Storage\Inu.Kernel.Storage.csproj" />
    <ProjectReference Include="..\Inu.Kernel.Heap\Inu.Kernel.Heap.csproj" />
  </ItemGroup>
</Project>
