<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <RootNamespace>Inu.ManagedCompiler</RootNamespace>
    <AssemblyName>Inu.ManagedCompiler</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Inu.ProjectModel\Inu.ProjectModel.csproj" />
  </ItemGroup>
</Project>
