using System;
using Inu.Kernel.Drivers;
using Inu.Kernel.Heap;

namespace Inu.Kernel.Networking;

public static unsafe partial class KernelNetworking
{
    public static Boolean RegisterInterface(KernelDeviceHandle device,KernelMacAddress mac,UInt32 mtu,KernelNetworkInterfaceCallbacks callbacks,out KernelNetworkInterfaceHandle handle){handle=default;if(!_initialized||device.Value==0||mac.IsZero||mtu<576||callbacks.TransmitFrame==null)return false;Int32 slot=FreeInterface();if(slot<0){if(!GrowInterfaces())return false;slot=FreeInterface();if(slot<0)return false;}InterfaceRecord* r=_interfaces+slot;r->Used=1;r->Device=device.Value;r->A=mac.A;r->B=mac.B;r->C=mac.C;r->D=mac.D;r->E=mac.E;r->F=mac.F;r->Mtu=mtu;r->Tx=callbacks.TransmitFrame;r->RxEnable=callbacks.SetReceiveEnabled;_interfacesUsed++;handle=new KernelNetworkInterfaceHandle((UInt32)slot+1U);return true;}
    /// <summary>Registers an interface using callbacks that receive the owning generic device handle.</summary>
    public static Boolean RegisterInterface(KernelDeviceHandle device,KernelMacAddress mac,UInt32 mtu,KernelContextualNetworkInterfaceCallbacks callbacks,out KernelNetworkInterfaceHandle handle){handle=default;if(!_initialized||device.Value==0||mac.IsZero||mtu<576||callbacks.TransmitFrame==null)return false;Int32 slot=FreeInterface();if(slot<0){if(!GrowInterfaces())return false;slot=FreeInterface();if(slot<0)return false;}InterfaceRecord* r=_interfaces+slot;r->Used=1;r->Contextual=1;r->Device=device.Value;r->A=mac.A;r->B=mac.B;r->C=mac.C;r->D=mac.D;r->E=mac.E;r->F=mac.F;r->Mtu=mtu;r->Tx=(delegate*<Byte*,UInt32,Boolean>)(void*)callbacks.TransmitFrame;r->RxEnable=(delegate*<Boolean,Boolean>)(void*)callbacks.SetReceiveEnabled;_interfacesUsed++;handle=new KernelNetworkInterfaceHandle((UInt32)slot+1U);return true;}
    /// <summary>Unregisters an interface and atomically removes routes/neighbours that depend on it.</summary>
    public static Boolean UnregisterInterface(KernelNetworkInterfaceHandle handle){if(!TryInterface(handle,out InterfaceRecord* r))return false;if(r->RxEnable!=null){if(r->Contextual!=0){delegate*<KernelDeviceHandle,Boolean,Boolean> rx=(delegate*<KernelDeviceHandle,Boolean,Boolean>)(void*)r->RxEnable;if(!rx(new KernelDeviceHandle(r->Device),false))return false;}else if(!r->RxEnable(false))return false;}KernelNetworkExtensionServices.RemoveInterface(handle);Clear((Byte*)r,sizeof(InterfaceRecord));if(_interfacesUsed>0U)_interfacesUsed--;return true;}

    public static Boolean ConfigureIpv4(KernelNetworkInterfaceHandle handle,KernelIpv4Address address,KernelIpv4Address mask,KernelIpv4Address gateway){if(!TryInterface(handle,out InterfaceRecord* r)||address.Value==0||mask.Value==0)return false;r->Address=address.Value;r->Mask=mask.Value;r->Gateway=gateway.Value;return true;}
    public static Boolean ConfigureIpv6(KernelNetworkInterfaceHandle handle,KernelIpv6Address address,Byte prefixLength){if(!TryInterface(handle,out InterfaceRecord* r)||address.IsUnspecified||prefixLength>128)return false;r->Address6High=address.High;r->Address6Low=address.Low;r->Prefix6=prefixLength;return true;}
    public static Boolean TryGetIpv6Configuration(KernelNetworkInterfaceHandle handle,out KernelIpv6Address address,out Byte prefixLength){address=default;prefixLength=0;if(!TryInterface(handle,out InterfaceRecord* r)||r->Address6High==0&&r->Address6Low==0)return false;address=new KernelIpv6Address(r->Address6High,r->Address6Low);prefixLength=r->Prefix6;return true;}
    public static Boolean SetInterfaceState(KernelNetworkInterfaceHandle handle,KernelNetworkInterfaceState state){if(!TryInterface(handle,out InterfaceRecord* r))return false;if(r->RxEnable!=null){Boolean enabled=state==KernelNetworkInterfaceState.Up;if(r->Contextual!=0){delegate*<KernelDeviceHandle,Boolean,Boolean> rx=(delegate*<KernelDeviceHandle,Boolean,Boolean>)(void*)r->RxEnable;if(!rx(new KernelDeviceHandle(r->Device),enabled))return false;}else if(!r->RxEnable(enabled))return false;}r->State=(Byte)state;return true;}
    public static Boolean TryGetInterface(KernelNetworkInterfaceHandle handle,out KernelNetworkInterfaceInfo info){info=default;if(!TryInterface(handle,out InterfaceRecord* r))return false;info=new(handle,new KernelDeviceHandle(r->Device),new KernelMacAddress(r->A,r->B,r->C,r->D,r->E,r->F),new KernelIpv4Address(r->Address),new KernelIpv4Address(r->Mask),new KernelIpv4Address(r->Gateway),r->Mtu,(KernelNetworkInterfaceState)r->State);return true;}
}
