using System;
namespace Inu.Kernel.Networking;

public static unsafe class KernelDnsCodec
{
    public static Boolean Register()=>KernelNetworkProtocolServices.RegisterDnsCodec(&BuildQueryForService,&ParseAForService,&ParseAaaaForService);
    private static Boolean BuildQueryForService(Byte* buffer,UInt32 capacity,UInt16 transactionId,String host,KernelDnsRecordType recordType,UInt32* length){if(length==null)return false;UInt32 value=0;if(!BuildQuery(buffer,capacity,transactionId,host,recordType,out value))return false;*length=value;return true;}
    private static Boolean ParseAForService(Byte* packet,UInt32 length,UInt16 transactionId,KernelIpv4Address* address){if(address==null)return false;KernelIpv4Address value=default;if(!TryParseAResponse(packet,length,transactionId,out value))return false;*address=value;return true;}
    private static Boolean ParseAaaaForService(Byte* packet,UInt32 length,UInt16 transactionId,KernelIpv6Address* address){if(address==null)return false;KernelIpv6Address value=default;if(!TryParseAaaaResponse(packet,length,transactionId,out value))return false;*address=value;return true;}
    private static Boolean BuildQuery(Byte* buffer,UInt32 capacity,UInt16 transactionId,String host,KernelDnsRecordType recordType,out UInt32 length){length=0;if(buffer==null||host==null||host.Length==0||capacity<17)return false;for(UInt32 i=0;i<capacity;i++)buffer[i]=0;KernelNetworkMath.WriteUInt16Network(buffer,2,transactionId);KernelNetworkMath.WriteUInt16Network(buffer+2,2,0x0100);KernelNetworkMath.WriteUInt16Network(buffer+4,2,1);UInt32 at=12,labelStart=0;for(Int32 i=0;i<=host.Length;i++){Boolean end=i==host.Length||host[i]=='.';if(!end)continue;Int32 labelLength=i-(Int32)labelStart;if(labelLength<=0||labelLength>63||at+1U+(UInt32)labelLength+5U>capacity)return false;buffer[at++]=(Byte)labelLength;for(Int32 j=0;j<labelLength;j++){Char c=host[(Int32)labelStart+j];if(c>127)return false;buffer[at++]=(Byte)c;}labelStart=(UInt32)i+1U;}buffer[at++]=0;KernelNetworkMath.WriteUInt16Network(buffer+at,2,(UInt16)recordType);at+=2;KernelNetworkMath.WriteUInt16Network(buffer+at,2,1);at+=2;length=at;return true;}
    private static Boolean TryParseAResponse(Byte* packet,UInt32 length,UInt16 transactionId,out KernelIpv4Address address){address=default;if(packet==null||length<12||KernelNetworkMath.ReadUInt16Network(packet)!=transactionId||(KernelNetworkMath.ReadUInt16Network(packet+2)&0x8000)==0)return false;UInt16 questions=KernelNetworkMath.ReadUInt16Network(packet+4),answers=KernelNetworkMath.ReadUInt16Network(packet+6);UInt32 at=12;for(UInt16 q=0;q<questions;q++){if(!SkipName(packet,length,ref at)||at+4>length)return false;at+=4;}for(UInt16 a=0;a<answers;a++){if(!SkipName(packet,length,ref at)||at+10>length)return false;UInt16 type=KernelNetworkMath.ReadUInt16Network(packet+at);UInt16 klass=KernelNetworkMath.ReadUInt16Network(packet+at+2);UInt16 dataLength=KernelNetworkMath.ReadUInt16Network(packet+at+8);at+=10;if(at+(UInt32)dataLength>length)return false;if(type==1&&klass==1&&dataLength==4){address=new KernelIpv4Address(KernelNetworkMath.ReadUInt32Network(packet+at));return true;}at+=(UInt32)dataLength;}return false;}
    private static Boolean TryParseAaaaResponse(Byte* packet,UInt32 length,UInt16 transactionId,out KernelIpv6Address address){address=default;if(packet==null||length<12||KernelNetworkMath.ReadUInt16Network(packet)!=transactionId||(KernelNetworkMath.ReadUInt16Network(packet+2)&0x8000)==0)return false;UInt16 questions=KernelNetworkMath.ReadUInt16Network(packet+4),answers=KernelNetworkMath.ReadUInt16Network(packet+6);UInt32 at=12;for(UInt16 q=0;q<questions;q++){if(!SkipName(packet,length,ref at)||at+4>length)return false;at+=4;}for(UInt16 a=0;a<answers;a++){if(!SkipName(packet,length,ref at)||at+10>length)return false;UInt16 type=KernelNetworkMath.ReadUInt16Network(packet+at);UInt16 klass=KernelNetworkMath.ReadUInt16Network(packet+at+2);UInt16 dataLength=KernelNetworkMath.ReadUInt16Network(packet+at+8);at+=10;if(at+(UInt32)dataLength>length)return false;if(type==28&&klass==1&&dataLength==16){address=KernelNetworkMath.ReadIpv6Address(packet+at);return true;}at+=(UInt32)dataLength;}return false;}
    private static Boolean SkipName(Byte* packet,UInt32 length,ref UInt32 at){while(at<length){Byte size=packet[at++];if(size==0)return true;if((size&0xC0)==0xC0){if(at>=length)return false;at++;return true;}if(size>63||at+(UInt32)size>length)return false;at+=(UInt32)size;}return false;}
}
