using System;
using Inu.Bus.Usb;
using Inu.Kernel.Drivers;
namespace Inu.Usb.Hub;
public readonly struct UsbHubCapabilities{public UsbHubCapabilities(Boolean initialized,UInt32 hubs,UInt32 ports,UInt32 downstreamDevices){Initialized=initialized;Hubs=hubs;Ports=ports;DownstreamDevices=downstreamDevices;}public Boolean Initialized{get;}public UInt32 Hubs{get;}public UInt32 Ports{get;}public UInt32 DownstreamDevices{get;}}
public static unsafe class UsbHub
{
 private struct HubRec{internal Byte Used,Device,Interface,Ports;internal UInt32 Generic;}
 private const Int32 Max=16;private static HubRec* _h;private static Inu.Kernel.Heap.KernelHeapAllocation _a;private static Boolean _initialized;private static KernelDriverHandle _driver;private static UInt32 _hubs,_ports,_downstream;
 public static Boolean Initialize(){if(_initialized)return true;if(!Inu.Kernel.Heap.KernelHeap.TryAllocate((UInt64)Max*(UInt64)sizeof(HubRec),64,true,out _a))return false;_h=(HubRec*)(nuint)_a.Address;KernelDriverMatchRule rule=new(KernelDeviceBus.Usb,true,0,false,0,false,0x090000U,0xFF0000U);KernelDriverCallbacks cb=new(&Probe,&Start,&Stop,&Remove,null);if(!KernelDrivers.RegisterDriver("usb-hub",rule,cb,out _driver)){Inu.Kernel.Heap.KernelHeap.TryRelease(_a);return false;}_initialized=true;return Discover();}
 public static Boolean Discover(){if(!_initialized)return false;for(UInt32 i=0;i<KernelUsbBus.GetInterfaceCount();i++){if(!KernelUsbBus.TryGetInterface(i,out UsbInterfaceInfo inf)||inf.Descriptor.Class!=(Byte)UsbClassCode.Hub||inf.DeviceNode.Value==0U)continue;if(!KernelDrivers.MatchAndStartDevice(inf.DeviceNode)&&FindGeneric(inf.DeviceNode)<0)return false;}return true;}
 public static Boolean EnumerateDownstream(){if(!_initialized)return false;for(Int32 i=0;i<Max;i++){HubRec* h=_h+i;if(h->Used!=0&&!EnumerateHub(h))return false;}return true;}
 public static UsbHubCapabilities GetCapabilities()=>new(_initialized,_hubs,_ports,_downstream);
 private static Boolean Probe(KernelDriverDeviceContext* c)=>c!=null&&KernelUsbBus.TryGetInterface(c->Device,out UsbInterfaceInfo inf)&&inf.Descriptor.Class==(Byte)UsbClassCode.Hub;
 private static Boolean Start(KernelDriverDeviceContext* c){if(c==null||FindGeneric(c->Device)>=0||!KernelUsbBus.TryGetInterface(c->Device,out UsbInterfaceInfo inf))return c!=null&&FindGeneric(c->Device)>=0;Byte* d=stackalloc Byte[12];UsbSetupPacket get=new(0xA0,6,0x2900,0,12);if(!KernelUsbBus.ControlTransfer(inf.Device,get,d,12,out UInt32 got)||got<7){get=new UsbSetupPacket(0xA0,6,0x2A00,0,12);if(!KernelUsbBus.ControlTransfer(inf.Device,get,d,12,out got)||got<7)return false;}Byte ports=d[2];Int32 s=Free();if(s<0)return false;HubRec* h=_h+s;h->Used=1;h->Device=(Byte)inf.Device.Value;h->Interface=inf.Descriptor.Number;h->Ports=ports;h->Generic=c->Device.Value;if(!KernelUsbBus.ConfigureHub(inf.Device,ports,false)||!PowerPorts(inf.Device,ports)){Clear((Byte*)h,(UInt32)sizeof(HubRec));return false;}_hubs++;_ports+=ports;return EnumerateHub(h);}
 private static Boolean Stop(KernelDriverDeviceContext* c){if(c==null)return false;Int32 i=FindGeneric(c->Device);if(i<0)return true;HubRec* h=_h+i;if(h->Ports<=_ports)_ports-=h->Ports;if(_hubs>0U)_hubs--;Clear((Byte*)h,(UInt32)sizeof(HubRec));return true;}
 private static Boolean Remove(KernelDriverDeviceContext* c)=>Stop(c);
 private static Boolean EnumerateHub(HubRec* h){UsbDeviceHandle hub=new(h->Device);if(!KernelUsbBus.TryGetDevice(hub,out UsbDeviceInfo hi))return false;for(Byte p=1;p<=h->Ports;p++){if(!GetPortStatus(hub,p,out UInt32 status)||(status&1U)==0)continue;if((status&(1U<<1))==0){SetPortFeature(hub,p,4);if(!GetPortStatus(hub,p,out status)||(status&(1U<<1))==0)continue;}UsbSpeed speed=(status&(1U<<9))!=0?UsbSpeed.Low:(status&(1U<<10))!=0?UsbSpeed.High:UsbSpeed.Full;if(KernelUsbBus.EnumeratePort(hi.Host,hi.Address,p,speed,out _))_downstream++;}return true;}
 private static Boolean PowerPorts(UsbDeviceHandle h,Byte ports){Boolean ok=true;for(Byte p=1;p<=ports;p++)if(!SetPortFeature(h,p,8))ok=false;return ok;}private static Boolean SetPortFeature(UsbDeviceHandle h,Byte port,UInt16 feature){UsbSetupPacket s=new(0x23,3,feature,port,0);return KernelUsbBus.ControlTransfer(h,s,null,0,out _);}private static Boolean GetPortStatus(UsbDeviceHandle h,Byte port,out UInt32 status){status=0;Byte* b=stackalloc Byte[4];UsbSetupPacket s=new(0xA3,0,0,port,4);if(!KernelUsbBus.ControlTransfer(h,s,b,4,out UInt32 n)||n!=4)return false;status=(UInt32)b[0]|((UInt32)b[1]<<8)|((UInt32)b[2]<<16)|((UInt32)b[3]<<24);return true;}private static Int32 FindGeneric(KernelDeviceHandle d){for(Int32 i=0;i<Max;i++)if((_h+i)->Used!=0&&(_h+i)->Generic==d.Value)return i;return -1;}private static Int32 Free(){for(Int32 i=0;i<Max;i++)if((_h+i)->Used==0)return i;return -1;}private static void Clear(Byte* p,UInt32 n){for(UInt32 i=0;i<n;i++)p[i]=0;}
}
