using System;
using Inu.Bus.Usb;
using Inu.Kernel.AddressSpace;
using Inu.Kernel.Drivers;
using Inu.Kernel.Heap;
using Inu.Kernel.Memory;
using Inu.Kernel.Pci;
namespace Inu.Usb.Xhci;
/// <summary>PCI xHCI host-controller implementation with command, event and endpoint transfer rings.</summary>
public static unsafe partial class KernelXhci
{
 static Boolean PrepareDevice(UInt64 context,Byte parentAddress,Byte port,UsbSpeed speed,Byte logicalAddress){Controller* c=(Controller*)(nuint)context;if(c==null||port==0)return false;Byte root=port,depth=0,parentSlot=0,ttPort=0;UInt32 route=0;Byte speedId=SpeedId(speed);if(parentAddress==0){if(port>c->Ports||!ResetRootPort(c,port,out speedId))return false;}else{Slot* parent=FindSlot(c,parentAddress);if(parent==null||parent->Depth>=5)return false;parentSlot=parent->SlotId;root=parent->RootPort;depth=(Byte)(parent->Depth+1);UInt32 nibble=port>15?(UInt32)15:port;route=parent->Route|(nibble<<(parent->Depth*4));if((speed==UsbSpeed.Low||speed==UsbSpeed.Full)&&parent->SpeedId==3){ttPort=port;}}
 if(!Command(c,0,0,0,9U<<10,out Byte slotId))return false;Slot* s=Slots(c)+slotId;if(s->Used!=0)return false;Clear((Byte*)s,(UInt64)sizeof(Slot));s->Used=1;s->SlotId=slotId;s->LogicalAddress=logicalAddress;s->RootPort=root;s->Depth=depth;s->SpeedId=speedId;s->Route=route;s->ParentSlot=parentSlot;s->TtPort=ttPort;s->Ep0Packet=DefaultEp0(speedId);s->ContextEntries=1;if(!Page(out s->Output)||!Page(out s->Input)||!Page(out s->Ep0.Memory))return Disable(c,s);Zero(s->Output);Zero(s->Input);Zero(s->Ep0.Memory);SetupTransferRing(&s->Ep0);((UInt64*)Direct(c->Dcbaa))[slotId]=s->Output.StartAddress;BuildInput(c,s,1,null);if(!Command(c,s->Input.StartAddress,0,0,(11U<<10)|((UInt32)slotId<<24),out _))return Disable(c,s);c->PendingSlot=slotId;return true;}
 static Boolean ControlTransfer(UInt64 context,Byte address,Byte endpoint,UsbSetupPacket* setup,Byte* buffer,UInt32 bytes,UInt32* transferred){Controller* c=(Controller*)(nuint)context;if(transferred!=null)*transferred=0;if(c==null||setup==null||endpoint!=0)return false;Slot* s=address==0?SlotById(c,c->PendingSlot):FindSlot(c,address);if(s==null)return false;if(setup->RequestType==0&&setup->Request==5){if(transferred!=null)*transferred=0;return true;}Boolean input=(setup->RequestType&0x80)!=0;KernelPhysicalAllocation bounce=default;Byte* dma=null;if(bytes!=0){if(!Buffer(bytes,out bounce,out dma))return false;if(!input&&buffer!=null)Copy(buffer,dma,bytes);}UInt64 setupValue=(UInt64)setup->RequestType|((UInt64)setup->Request<<8)|((UInt64)setup->Value<<16)|((UInt64)setup->Index<<32)|((UInt64)setup->Length<<48);UInt32 trt=bytes==0?0U:(input?3U:2U);if(!Enqueue(&s->Ep0,setupValue,0,8U,(2U<<10)|(1U<<6)|(trt<<16)|(bytes!=0?1U<<4:0U))){Release(bounce);return false;}if(bytes!=0&&!Enqueue(&s->Ep0,bounce.StartAddress,0,bytes,(3U<<10)|(input?1U<<16:0U)|(1U<<4))){Release(bounce);return false;}Boolean statusIn=bytes==0||!input;if(!Enqueue(&s->Ep0,0,0,0,(4U<<10)|(statusIn?1U<<16:0U)|(1U<<5))){Release(bounce);return false;}RingDoorbell(c,s->SlotId,1);Boolean ok=WaitTransfer(c,s->SlotId,1,bytes,out UInt32 actual);if(ok&&bytes!=0&&input&&buffer!=null)Copy(dma,buffer,actual);if(ok&&input&&setup->Request==6&&(setup->Value>>8)==1&&actual>=8&&dma[7]!=s->Ep0Packet)ok=UpdateEp0(c,s,dma[7]);Release(bounce);if(transferred!=null)*transferred=actual;return ok;}
 static Boolean ConfigureEndpoint(UInt64 context,Byte address,UsbEndpointDescriptor* descriptor){Controller* c=(Controller*)(nuint)context;if(c==null||descriptor==null||descriptor->Number==0)return false;Slot* s=FindSlot(c,address);if(s==null)return false;Byte dci=Dci(descriptor->Address);if(FindEndpoint(c,s->SlotId,dci)!=null)return true;Endpoint* e=FreeEndpoint(c);if(e==null)return false;Clear((Byte*)e,(UInt64)sizeof(Endpoint));e->Used=1;e->SlotId=s->SlotId;e->Dci=dci;e->Address=descriptor->Address;e->Type=(Byte)descriptor->TransferType;e->Interval=descriptor->Interval;e->MaxPacket=descriptor->MaximumPacketSize;if(!Page(out e->Ring.Memory)){e->Used=0;return false;}Zero(e->Ring.Memory);SetupTransferRing(&e->Ring);if(dci>s->ContextEntries)s->ContextEntries=dci;BuildInput(c,s,dci,e);if(!Command(c,s->Input.StartAddress,0,0,(12U<<10)|((UInt32)s->SlotId<<24),out _)){Release(e->Ring.Memory);e->Used=0;return false;}return true;}
 static Boolean ConfigureHub(UInt64 context,Byte address,Byte ports,Boolean multiTt){Controller* c=(Controller*)(nuint)context;if(c==null)return false;Slot* s=FindSlot(c,address);if(s==null)return false;s->HubPorts=ports;s->MultiTt=multiTt?(Byte)1:(Byte)0;BuildInput(c,s,0,null);return Command(c,s->Input.StartAddress,0,0,(13U<<10)|((UInt32)s->SlotId<<24),out _);}
 static Boolean BulkTransfer(UInt64 context,Byte address,Byte endpoint,Byte* buffer,UInt32 bytes,UInt32* transferred)=>DataTransfer((Controller*)(nuint)context,address,endpoint,buffer,bytes,transferred);
 static Boolean InterruptTransfer(UInt64 context,Byte address,Byte endpoint,Byte* buffer,UInt32 bytes,UInt32* transferred)=>DataTransfer((Controller*)(nuint)context,address,endpoint,buffer,bytes,transferred);
 static Boolean DataTransfer(Controller* c,Byte address,Byte endpoint,Byte* buffer,UInt32 bytes,UInt32* transferred){if(transferred!=null)*transferred=0;if(c==null||buffer==null||bytes==0||bytes>4096)return false;Slot* s=FindSlot(c,address);if(s==null)return false;Byte dci=Dci(endpoint);Endpoint* e=FindEndpoint(c,s->SlotId,dci);if(e==null)return false;Boolean input=(endpoint&0x80)!=0;if(!Buffer(bytes,out KernelPhysicalAllocation bounce,out Byte* dma))return false;if(!input)Copy(buffer,dma,bytes);if(!Enqueue(&e->Ring,bounce.StartAddress,0,bytes,(1U<<10)|(1U<<2)|(1U<<5))){Release(bounce);return false;}RingDoorbell(c,s->SlotId,dci);Boolean ok=WaitTransfer(c,s->SlotId,dci,bytes,out UInt32 actual);if(ok&&input)Copy(dma,buffer,actual);Release(bounce);if(transferred!=null)*transferred=actual;return ok;}
 static Boolean UpdateEp0(Controller* c,Slot* s,UInt16 packet){if(packet==0||packet==s->Ep0Packet)return packet!=0;s->Ep0Packet=packet;BuildInput(c,s,1,null);return Command(c,s->Input.StartAddress,0,0,(13U<<10)|((UInt32)s->SlotId<<24),out _);}
 static void BuildInput(Controller* c,Slot* s,Byte addDci,Endpoint* e){Byte* input=Direct(s->Input);Clear(input,4096);UInt32* icc=(UInt32*)input;UInt32 flags=1U;if(addDci!=0)flags|=1U<<addDci;icc[1]=flags;UInt32* slot=(UInt32*)(input+c->ContextSize);slot[0]=(s->Route&0xFFFFFU)|((UInt32)s->SpeedId<<20)|((UInt32)s->MultiTt<<25)|(s->HubPorts!=0?1U<<26:0U)|((UInt32)s->ContextEntries<<27);slot[1]=((UInt32)s->RootPort<<16)|((UInt32)s->HubPorts<<24);if(s->TtPort!=0)slot[2]=(UInt32)s->ParentSlot|((UInt32)s->TtPort<<8);if(addDci==1){UInt32* ep=(UInt32*)(input+(UInt32)c->ContextSize*2U);BuildEndpointContext(ep,4,s->Ep0Packet,s->Ep0.Memory.StartAddress,0,8);}else if(e!=null){UInt32* ep=(UInt32*)(input+(UInt32)c->ContextSize*(UInt32)(e->Dci+1));Byte type=EndpointType(e->Address,(UsbTransferType)e->Type);BuildEndpointContext(ep,type,e->MaxPacket,e->Ring.Memory.StartAddress,Interval(s->SpeedId,(UsbTransferType)e->Type,e->Interval),e->MaxPacket);}}
 static void BuildEndpointContext(UInt32* ep,Byte type,UInt16 packet,UInt64 dequeue,Byte interval,UInt16 average){for(Int32 i=0;i<8;i++)ep[i]=0;ep[0]=(UInt32)interval<<16;ep[1]=(3U<<1)|((UInt32)type<<3)|((UInt32)packet<<16);ep[2]=(UInt32)dequeue|1U;ep[3]=(UInt32)(dequeue>>32);ep[4]=average;}
 static Boolean ResetRootPort(Controller* c,Byte port,out Byte speed){speed=0;UInt64 a=Port(c,port);UInt32 v=R32(a);if((v&1U)==0)return false;speed=(Byte)((v>>10)&15U);if((v&2U)!=0)return true;UInt32 write=(v&~0x00FE0000U)|(1U<<4);W32(a,write);for(UInt32 i=0;i<SpinLimit;i++){UInt32 p=R32(a);if((p&1U)==0)return false;if((p&(1U<<4))==0&&(p&2U)!=0){speed=(Byte)((p>>10)&15U);return true;}}return false;}
}
