using System;
using Inu.Bus.Usb;
using Inu.Kernel.AddressSpace;
using Inu.Kernel.Drivers;
using Inu.Kernel.Heap;
using Inu.Kernel.Memory;
using Inu.Kernel.Pci;
namespace Inu.Usb.Xhci;
/// <summary>PCI xHCI host-controller implementation with command, event and endpoint transfer rings.</summary>
public static unsafe partial class KernelXhci
{
 static Slot* FindSlot(Controller* c,Byte logical){if(logical==0)return null;Slot* t=Slots(c);for(Int32 i=1;i<MaxSlots;i++)if((t+i)->Used!=0&&(t+i)->LogicalAddress==logical)return t+i;return null;}static Slot* SlotById(Controller* c,Byte id){if(id==0)return null;Slot* s=Slots(c)+id;return s->Used!=0?s:null;}static Slot* Slots(Controller* c)=>(Slot*)(nuint)c->SlotTable;
 static Endpoint* FindEndpoint(Controller* c,Byte slot,Byte dci){Endpoint* e=(Endpoint*)(nuint)c->EndpointTable;for(Int32 i=0;i<MaxEndpoints;i++)if((e+i)->Used!=0&&(e+i)->SlotId==slot&&(e+i)->Dci==dci)return e+i;return null;}static Endpoint* FreeEndpoint(Controller* c){Endpoint* e=(Endpoint*)(nuint)c->EndpointTable;for(Int32 i=0;i<MaxEndpoints;i++)if((e+i)->Used==0)return e+i;return null;}
 static Controller* FindController(KernelDeviceHandle device){for(Int32 i=0;i<MaxControllers;i++)if((_controllers+i)->Used!=0&&(_controllers+i)->DeviceHandle==device.Value)return _controllers+i;return null;}static Int32 FreeController(){for(Int32 i=0;i<MaxControllers;i++)if((_controllers+i)->Used==0)return i;return -1;}
 static Boolean ReleaseControllerResources(Controller* c){if(c==null)return false;Boolean ok=true;if(c->EndpointTable!=0UL){Endpoint* e=(Endpoint*)(nuint)c->EndpointTable;for(Int32 i=0;i<MaxEndpoints;i++)if((e+i)->Used!=0&&e[i].Ring.Memory.Token!=0)ok=Release(e[i].Ring.Memory)&ok;}if(c->SlotTable!=0UL){Slot* s=(Slot*)(nuint)c->SlotTable;for(Int32 i=1;i<MaxSlots;i++)if((s+i)->Used!=0){ok=Release(s[i].Output)&ok;ok=Release(s[i].Input)&ok;ok=Release(s[i].Ep0.Memory)&ok;}}ok=Release(c->Dcbaa)&ok;ok=Release(c->Command)&ok;ok=Release(c->Event)&ok;ok=Release(c->Erst)&ok;ok=Release(c->ScratchArray)&ok;ok=Release(c->ScratchPages)&ok;if(c->SlotAllocation.Token!=0UL)ok=KernelHeap.TryRelease(c->SlotAllocation)&ok;if(c->EndpointAllocation.Token!=0UL)ok=KernelHeap.TryRelease(c->EndpointAllocation)&ok;c->SlotTable=0UL;c->EndpointTable=0UL;return ok;}
 static Boolean Disable(Controller* c,Slot* s){if(s->SlotId!=0)Command(c,0,0,0,(10U<<10)|((UInt32)s->SlotId<<24),out _);Release(s->Output);Release(s->Input);Release(s->Ep0.Memory);Clear((Byte*)s,(UInt64)sizeof(Slot));return false;}
 static Byte Dci(Byte address){Byte n=(Byte)(address&15U);return (Byte)(n*2U+((address&0x80)!=0?1U:0U));}static Byte EndpointType(Byte address,UsbTransferType type){Boolean input=(address&0x80)!=0;if(type==UsbTransferType.Isochronous)return input?(Byte)5:(Byte)1;if(type==UsbTransferType.Bulk)return input?(Byte)6:(Byte)2;if(type==UsbTransferType.Interrupt)return input?(Byte)7:(Byte)3;return 4;}
 static Byte Interval(Byte speedId,UsbTransferType type,Byte value){if(value==0)return 0;if(speedId>=3)return (Byte)(value>16?15:value-1);UInt32 target=(UInt32)value*8U,exp=0,p=1;while(p<target&&exp<15){p<<=1;exp++;}return (Byte)(exp==0?0:exp-1);}
 static Byte SpeedId(UsbSpeed s)=>s==UsbSpeed.Full?(Byte)1:s==UsbSpeed.Low?(Byte)2:s==UsbSpeed.High?(Byte)3:s==UsbSpeed.Super?(Byte)4:s==UsbSpeed.SuperPlus?(Byte)5:(Byte)0;static UsbSpeed SpeedFromId(Byte s)=>s==1?UsbSpeed.Full:s==2?UsbSpeed.Low:s==3?UsbSpeed.High:s==4?UsbSpeed.Super:s==5?UsbSpeed.SuperPlus:UsbSpeed.Unknown;static UInt16 DefaultEp0(Byte s)=>s>=4?(UInt16)512:s==3?(UInt16)64:(UInt16)8;
 static UInt64 Port(Controller* c,Byte p)=>c->Operational+0x400UL+(UInt64)(p-1)*0x10UL;static Boolean Page(out KernelPhysicalAllocation a)=>KernelPhysicalMemory.TryAllocate(1,1,out a);static Boolean Buffer(UInt32 bytes,out KernelPhysicalAllocation a,out Byte* p){a=default;p=null;UInt64 pages=((UInt64)bytes+4095UL)/4096UL;if(!KernelPhysicalMemory.TryAllocate(pages,1,out a))return false;p=Direct(a);Zero(a);return true;}static Byte* Direct(KernelPhysicalAllocation a)=>(Byte*)(nuint)(KernelAddressSpace.DirectMapBase+a.StartAddress);static void Zero(KernelPhysicalAllocation a){if(a.Token==0)return;Clear(Direct(a),a.PageCount*4096UL);}static Boolean Release(KernelPhysicalAllocation a)=>a.Token==0||KernelPhysicalMemory.TryRelease(a);
 static Boolean Wait32(UInt64 a,UInt32 mask,UInt32 expected){for(UInt32 i=0;i<SpinLimit;i++)if((R32(a)&mask)==expected)return true;return false;}static Byte R8(UInt64 a)=>*(Byte*)(nuint)a;static UInt32 R32(UInt64 a)=>*(UInt32*)(nuint)a;static void W32(UInt64 a,UInt32 v)=>*(UInt32*)(nuint)a=v;static void W64(UInt64 a,UInt64 v)=>*(UInt64*)(nuint)a=v;static void Clear(Byte* p,UInt64 n){for(UInt64 i=0;i<n;i++)p[i]=0;}static void Copy(Byte* s,Byte* d,UInt32 n){for(UInt32 i=0;i<n;i++)d[i]=s[i];}
}
